# Python-Numpy vectors

In [1]:
import numpy as np

In [4]:
a = np.random.randn(5)

print(a)

[ 0.59222057  0.59055104 -0.49366224 -1.8213608   0.52659094]


In [5]:
print(a.shape)

(5,)


This is what we call a rank 1 array. We should not use rank 1 arrays structure when training NNs. 

In [6]:
print(a.T)

[ 0.59222057  0.59055104 -0.49366224 -1.8213608   0.52659094]


As a rank 1 array, its transpose ends up looking exactly the same. Instead, when training NNs we should be using column vectors (e.g. size (5, 1)) or row vectors (e.g. size (1,5)); aka “n by 1” and “1 by n” matrices.

In [9]:
a = np.random.randn(5, 1)

print(a)

[[ 0.79599305]
 [-0.85235005]
 [-0.75106449]
 [ 0.08159798]
 [-0.83653523]]


In [10]:
print(a.T)

[[ 0.79599305 -0.85235005 -0.75106449  0.08159798 -0.83653523]]


In [11]:
print(np.dot(a, a.T))

[[ 0.63360493 -0.67846472 -0.59784211  0.06495143 -0.66587623]
 [-0.67846472  0.72650061  0.64016986 -0.06955004  0.71302085]
 [-0.59784211  0.64016986  0.56409786 -0.06128535  0.62829191]
 [ 0.06495143 -0.06955004 -0.06128535  0.00665823 -0.06825959]
 [-0.66587623  0.71302085  0.62829191 -0.06825959  0.6997912 ]]


This does give us the outer product of a vector, which is a matrix with dimensions